run:
  timeout: 5m
  skip-dirs:
    - bin
    - vendor
    - mocks

linters:
  enable:
    - gofmt
    - goimports
    - revive
    - govet
    - staticcheck
    - unused
    - ineffassign
    - typecheck
    - errcheck
    - stylecheck
    - unconvert
    - goconst
    - gocyclo
    - gocritic
    - godot
    - godox
    - gofumpt
    - importas
    - misspell
    - prealloc
    - whitespace

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - funlen
        - goconst
        - gocritic
        - gocyclo
